import { dialog, ipcMain, shell } from 'electron'
import { mkdir, writeFile, readdir, stat } from 'fs/promises'
import { existsSync } from 'fs'
import { dirname, join } from 'path'
import { IPC } from '../../shared/ipc'
import type { ArtemisProject } from '../../shared/project'
import { toPascalCase } from '../../shared/project'
import { CodeGenerator } from '../../shared/generator/CodeGenerator'
import { getMapping } from '../../shared/generator/mappings'
import { textureSlotsFor } from '../../shared/generator/textures'
import { runGradle } from '../gradle'

interface ExportResult {
  ok: boolean
  path?: string
  jarPath?: string
  error?: string
  log: string[]
}

async function findBuiltJar(root: string): Promise<string | null> {
  const libsDir = join(root, 'build', 'libs')
  if (!existsSync(libsDir)) return null
  const candidates = (await readdir(libsDir)).filter(
    (f) => f.endsWith('.jar') && !f.endsWith('-dev.jar') && !f.endsWith('-sources.jar')
  )
  if (!candidates.length) return null
  const withTime = await Promise.all(
    candidates.map(async (f) => ({ f, mtime: (await stat(join(libsDir, f))).mtimeMs }))
  )
  withTime.sort((a, b) => b.mtime - a.mtime)
  return join(libsDir, withTime[0].f)
}

export function registerExportIpc(): void {
  ipcMain.handle(IPC.ExportWorkspace, async (_e, projectJson: string): Promise<ExportResult> => {
    const log: string[] = []
    try {
      const project = JSON.parse(projectJson) as ArtemisProject
      const res = await dialog.showOpenDialog({
        title: 'Choose export folder',
        properties: ['openDirectory', 'createDirectory']
      })
      if (res.canceled || res.filePaths.length === 0) {
        return { ok: false, error: 'Export cancelled.', log }
      }
      const root = join(res.filePaths[0], project.meta.modId)
      await exportWorkspace(project, root, log)

      log.push('')
      log.push('Building mod jar…')
      log.push('First build downloads Minecraft + dependencies and can take several minutes…')
      log.push('─'.repeat(60))
      const build = await runGradle(
        root,
        'build',
        (line) => log.push(line),
        getMapping(project.meta.targetBta).gradle.gradleVersion
      )
      const { code, signal } = await build.done
      log.push('─'.repeat(60))

      if (signal || code !== 0) {
        log.push(`✗ Build failed (${signal ? `signal ${signal}` : `exit code ${code}`}). Source is still at ${root}.`)
        return { ok: true, path: root, log }
      }

      const jarPath = await findBuiltJar(root)
      if (jarPath) log.push(`✓ Built ${jarPath}`)
      else log.push('✗ Build succeeded but no jar was found under build/libs.')

      return { ok: true, path: root, jarPath: jarPath ?? undefined, log }
    } catch (e) {
      log.push(`✗ ${e instanceof Error ? e.message : String(e)}`)
      return { ok: false, error: e instanceof Error ? e.message : String(e), log }
    }
  })

  ipcMain.on(IPC.ShellShowItemInFolder, (_e, path: string) => {
    shell.showItemInFolder(path)
  })
}

async function write(root: string, rel: string, content: string): Promise<void> {
  const abs = join(root, rel)
  await mkdir(dirname(abs), { recursive: true })
  await writeFile(abs, content, 'utf-8')
}

export async function exportWorkspace(
  project: ArtemisProject,
  root: string,
  log: string[]
): Promise<void> {
  const mapping = getMapping(project.meta.targetBta)
  const meta = project.meta

  log.push(`Exporting "${meta.name}" → ${root}`)

  const files = new CodeGenerator(project).generate()
  for (const f of files) {
    await write(root, f.path, f.content)
    log.push(`  + ${f.path}`)
  }

  const halplibeVersion = await resolveHalplibeVersion(mapping.gradle.halplibe, log)

  const g = mapping.gradle
  await write(
    root,
    'gradle.properties',
    `# Generated by Artemis
org.gradle.jvmargs=-Xmx2G

mod_version=${meta.version}
mod_group=com.${meta.modId}
mod_name=${meta.modId}

bta_version=${mapping.btaVersion}
loader_version=${g.fabricLoaderVersion}
# Latest halplibe at export time. Bump freely, Artemis re-resolves on re-export.
halplibe_version=${halplibeVersion}
`
  )

  await write(
    root,
    'settings.gradle',
    `pluginManagement {
	repositories {
		mavenCentral()
		gradlePluginPortal()
		maven { url = '${g.btaMaven}' }
		maven { url = '${g.babricMaven}' }
	}
}

rootProject.name = '${meta.modId}'
`
  )

  const obfuscate = meta.obfuscate !== false
  await write(
    root,
    'build.gradle',
    `// Generated by Artemis for Better Than Adventure! ${mapping.btaVersion}
${
  obfuscate
    ? `buildscript {
	repositories { mavenCentral() }
	dependencies { classpath 'com.guardsquare:proguard-gradle:${mapping.obfuscation.proguardVersion}' }
}
`
    : ''
}plugins {
	id 'java'
	id '${g.loomPlugin}' version '${g.loomVersion}'
}

group = project.mod_group
version = project.mod_version

java {
	sourceCompatibility = JavaVersion.toVersion(${g.javaVersion})
	targetCompatibility = JavaVersion.toVersion(${g.javaVersion})
}

repositories {
	mavenCentral()
	maven { url = '${g.btaMaven}' }
	maven { url = '${g.babricMaven}' }
}

dependencies {
	minecraft "bta:bta:\${project.bta_version}"
	mappings loom.layered {}

	modImplementation "babric:fabric-loader:\${project.loader_version}"
	// halplibe, fetched at the version Artemis resolved from the latest GitHub release
	modImplementation "${g.halplibe.mavenGroup}:${g.halplibe.artifact}:\${project.halplibe_version}"
}

processResources {
	inputs.property 'version', project.version
	filesMatching('fabric.mod.json') {
		expand 'version': project.version
	}
}

jar {
	from('LICENSE') { rename { "\${it}_\${project.archivesBaseName}" } }
}
${obfuscate ? obfuscationTask() : ''}`
  )

  if (obfuscate) {
    await write(root, 'proguard-rules.pro', proguardRules(project, mapping))
    log.push('  + build.gradle / settings.gradle / gradle.properties')
    log.push('  + proguard-rules.pro (obfuscation ON: name obfuscation plus stability keep-list)')
  } else {
    log.push('  + build.gradle / settings.gradle / gradle.properties (obfuscation OFF)')
  }

  const fmj = {
    ...mapping.fabricModJson,
    id: meta.modId,
    version: '${version}',
    name: meta.name,
    description: meta.description || `${meta.name}, a Better Than Adventure! mod.`,
    authors: meta.authors.length ? meta.authors : ['Unknown'],
    entrypoints: {
      main: [`com.${meta.modId}.${toPascalCase(meta.modId)}Mod`],
      beforeGameStart: [`com.${meta.modId}.${toPascalCase(meta.modId)}Mod`],
      recipesReady: [`com.${meta.modId}.${toPascalCase(meta.modId)}Mod`]
    },
    custom: {

      credits: [...meta.authors, 'Made using Artemis']
    }
  }
  await write(root, 'src/main/resources/fabric.mod.json', JSON.stringify(fmj, null, 2) + '\n')

  const credits = [
    `${meta.name} v${meta.version}`,
    '',
    ...(meta.authors.length ? ['Authors:', ...meta.authors.map((a) => `  ${a}`), ''] : []),
    'Made using Artemis'
  ].join('\n')
  await write(root, 'CREDITS.txt', credits + '\n')
  log.push('  + fabric.mod.json / CREDITS.txt (Artemis credit appended)')

  const assetDirs = ['block', 'item', 'entity']
  for (const d of assetDirs) {
    await write(
      root,
      `src/main/resources/assets/${meta.modId}/textures/${d}/.keep`,
      ''
    )
  }

  const slots = textureSlotsFor(project)
  const textureById = new Map((project.textures ?? []).map((t) => [t.id, t]))
  const assignments = project.textureAssignments ?? {}
  let written = 0
  const missing: typeof slots = []
  for (const slot of slots) {
    const tex = textureById.get(assignments[slot.key] ?? '')
    if (tex) {

      const base64 = tex.data.replace(/^data:image\/png;base64,/, '')
      const abs = join(root, `src/main/resources/assets/${meta.modId}/textures/${slot.key}.png`)
      await mkdir(dirname(abs), { recursive: true })
      await writeFile(abs, Buffer.from(base64, 'base64'))
      written++
    } else {
      missing.push(slot)
    }
  }

  await write(
    root,
    'TEXTURES_TODO.txt',
    missing.length === 0
      ? 'All referenced textures were painted in Artemis. Nothing left to add.\n'
      : [
          'Textures still needed (16x16 PNG unless noted).',
          'Paint them in Artemis and re-export, or drop the files in by hand:',
          '',
          ...missing.map(
            (s) =>
              `  src/main/resources/assets/${meta.modId}/textures/${s.key}.png${s.paintable ? '' : '  (64x32 entity skin)'}`
          ),
          ''
        ].join('\n')
  )
  log.push(`  + ${written} painted texture(s) written, ${missing.length} still missing (see TEXTURES_TODO.txt)`)

  log.push('')
  log.push(`Done. Open the folder in your IDE and run: gradlew build`)
}

function obfuscationTask(): string {
  return `
// ---- Artemis obfuscation ------------------------------------------------
// Runs after remapJar. Name obfuscation only (no shrink/optimize) with the
// keep-list in proguard-rules.pro. Output: <name>-obf.jar, which then
// replaces the distributable jar.
import proguard.gradle.ProGuardTask

tasks.register('obfuscateJar', ProGuardTask) {
	dependsOn tasks.named('remapJar')
	def input = tasks.named('remapJar').get().archiveFile.get().asFile
	def output = new File(input.parentFile, input.name.replaceFirst(/\\.jar$/, '-obf.jar'))

	injars input
	outjars output

	// full dependency surface so override names stay bound to library methods
	libraryjars configurations.runtimeClasspath
	// JDK modules ProGuard needs as a library reference
	libraryjars "\${System.getProperty('java.home')}/jmods/java.base.jmod", jarfilter: '!**.jar', filter: '!module-info.class'

	configuration 'proguard-rules.pro'

	doLast {
		// swap the obfuscated jar in for the normal artifact
		def dist = new File(input.parentFile, input.name)
		dist.delete()
		output.renameTo(dist)
		logger.lifecycle("Artemis: obfuscated jar written to \${dist.name}")
	}
}

// 'gradlew build' produces an obfuscated jar; the un-obfuscated remapJar
// output is replaced in place by obfuscateJar's doLast.
tasks.named('build').configure { finalizedBy 'obfuscateJar' }
tasks.named('assemble').configure { finalizedBy 'obfuscateJar' }
`
}

function proguardRules(project: ArtemisProject, mapping: ReturnType<typeof getMapping>): string {
  const pkg = `com.${project.meta.modId}`
  const entry = `${pkg}.${toPascalCase(project.meta.modId)}Mod`
  const o = mapping.obfuscation

  const reflectivePatterns = o.reflectiveClassPatterns.map((p) =>
    p.startsWith('**') ? `${pkg}${p.slice(2)}` : p
  )

  return `# ===================================================================
# proguard-rules.pro, generated by Artemis
# Name obfuscation with a stability keep-list for BTA / Fabric / halplibe.
#
# A Fabric mod CANNOT be fully name-mangled and still load: the loader finds
# entrypoints by name, Minecraft calls your overrides by name, halplibe builds
# entities reflectively, and registry IDs are string literals (untouched by
# obfuscation anyway). This config renames everything internal and keeps only
# the load-bearing symbols below.
# ===================================================================

# Rename only. Do NOT shrink or optimize. Shrinking dead-strips reflectively
# used members; optimization rewrites bytecode Mixin/loom can't follow.
-dontshrink
-dontoptimize
-dontpreverify
-verbose

# Attributes the loader, Mixin, and stack traces depend on.
-keepattributes *Annotation*,Signature,InnerClasses,EnclosingMethod,Exceptions,SourceFile,LineNumberTable,RuntimeVisibleAnnotations,RuntimeVisibleParameterAnnotations,RuntimeInvisibleAnnotations,AnnotationDefault
-keepparameternames
# keep a fake source name so stack traces still map to line numbers
-renamesourcefileattribute SourceFile

# --- Fabric entrypoints (referenced by FQN in fabric.mod.json) ---
-keep class ${entry} {
	public <init>(...);
	public *;
}

# --- Mixins (classes + members referenced by the mixin config and ASM) ---
-keep @${o.mixinPackage}.Mixin class * { *; }
-keepclassmembers class * {
	@${o.mixinPackage}.** *;
}
-keepnames class * extends ${o.mixinPackage}.extensibility.IMixinConfigPlugin

# --- Reflectively constructed classes (entities, world features): keep the
#     class name and constructors so factories/networking resolve them. ---
${reflectivePatterns.map((p) => `-keep class ${p} {\n\t<init>(...);\n\tpublic *;\n}`).join('\n')}

# --- Enums: values()/valueOf are reflection entry points. ---
-keepclassmembers enum * {
	public static **[] values();
	public static ** valueOf(java.lang.String);
}

# --- The library surface we compile against but don't ship. Suppress the
#     "can't find referenced class" notes/warnings for those packages;
#     -libraryjars in build.gradle supplies them at obfuscation time. ---
${o.minecraftPackages.map((p) => `-dontwarn ${p}`).join('\n')}
-dontwarn ${o.mixinPackage}.**
-dontwarn ${o.fabricApiPackage}.**
-dontnote **

# If ProGuard reports a missing class for a dependency you added by hand,
# add another '-libraryjars' line for it in build.gradle, or a '-dontwarn'
# here. Never use '-ignorewarnings', which hides real breakage.
`
}

async function resolveHalplibeVersion(
  h: { githubRepo: string; fallbackVersion: string },
  log: string[]
): Promise<string> {
  try {
    const res = await fetch(`https://api.github.com/repos/${h.githubRepo}/releases/latest`, {
      headers: { Accept: 'application/vnd.github+json', 'User-Agent': 'artemis-mod-maker' }
    })
    if (!res.ok) throw new Error(`GitHub API ${res.status}`)
    const data = (await res.json()) as { tag_name?: string }
    const tag = (data.tag_name ?? '').replace(/^v/, '')
    if (!tag) throw new Error('release has no tag')
    log.push(`  halplibe: latest release is ${tag}`)
    return tag
  } catch (e) {
    log.push(
      `  halplibe: could not reach GitHub (${e instanceof Error ? e.message : e}). Using pinned fallback ${h.fallbackVersion}`
    )
    return h.fallbackVersion
  }
}
